- name: Inject Secrets into EC2
  hosts: all
  become: yes

  tasks:
    - name: Install required system packages on Ubuntu
      apt:
        name:
          - unzip
          - curl
          - jq
        state: present
        update_cache: true

    - name: Download AWS CLI v2 installer for Ubuntu
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Unzip AWS CLI v2 installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install (or update) AWS CLI v2
      become: true
      command: "/tmp/aws/install --update"


    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Clone app repository
      git:
        repo: 'https://github.com/Maddie2030/assignment_project_2.git'
        dest: /home/ubuntu/app
        version: main
        force: yes

    - name: Build Docker image
      command:
        sudo usermod -aG docker ubuntu
      command:
        docker build -t my-python-app .
      args:
        chdir: /home/ubuntu/app

    - name: Run Docker container
      command: >
        docker run -d --name my-python-app-container
        -p 80:80
        my-python-app